### ISSUE TITLE
[BUG 🪲] [Python] Capture Session Threw An Exception -> Frame handler error

### ISSUE THREAD

**Issue by zipslide** [NiiightmareXD/windows-capture#101]
**Describe the bug 🐛**

Running the example, that you gave us. I'm using a fresh venv.

```python
(venv) PS C:\Users\test\win_cap> python wincap.py
Traceback (most recent call last):
  File "C:\Users\test\win_cap\wincap.py", line 31, in <module>
    capture.start()
  File "C:\Users\test\win_cap\venv\Lib\site-packages\windows_capture\__init__.py", line 207, in start
    self.capture.start()
Exception: Capture Session Threw An Exception -> Frame handler error: Frame Process Error: Windows API error: The parameter is incorrect. (0x80070057)
```

**OS 🤖**
Windows 11 Home, 23H2 (latest as of 11/10/24)

** Additional Context **

Python 3.11.9

Package         Version
--------------- ---------
numpy           2.1.3
opencv-python   4.10.0.84
pip             24.0
setuptools      65.5.0
windows-capture 1.4.0

**Comment by mycrl** [comment]
@Snoogens101 @zipslide Do you have the same problem running the rust example?

**Comment by Snoogens101** [comment]
> @Snoogens101 @zipslide Do you have the same problem running the rust example?

No, the issue does not exist in Rust, only when using the Python version.

**Comment by NiiightmareXD** [comment]
> > @Snoogens101 @zipslide Do you have the same problem running the rust example?
> 
> No, the issue does not exist in Rust, only when using the Python version.

Can you try the new version 1.4.2?

**Comment by Snoogens101** [comment]
> > > @Snoogens101 @zipslide Do you have the same problem running the rust example?
> > 
> > 
> > No, the issue does not exist in Rust, only when using the Python version.
> 
> Can you try the new version 1.4.2?

Works! Thank you very much :)
