### ISSUE TITLE
[BUG 🪲] Capture Session Threw An Exception -> Graphics Capture Error

### ISSUE THREAD

**Issue by rlewkowicz** [NiiightmareXD/windows-capture#5]
**Describe the bug 🐛**
```
Traceback (most recent call last):
  File "C:\Repos\yolov5\detect.py", line 51, in <module>
    from models.common import DetectMultiBackend
  File "C:\Repos\yolov5\models\common.py", line 41, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "C:\Repos\yolov5\utils\dataloaders.py", line 70, in <module>
    capture.start()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\site-packages\windows_capture\__init__.py", line 204, in start
    self.capture.start()
Exception: Capture Session Threw An Exception -> Graphics Capture Error
```
**Expected behavior 📝**
It captures the screen

**OS 🤖**
Edition	Windows 10 Pro
Version	22H2
Installed on	‎12/‎22/‎2022
OS build	19045.3570
Experience	Windows Feature Experience Pack 1000.19052.1000.0

**Additional context ➕**
This works on windows 11, interestingly enough https://github.com/rlewkowicz/Win32CaptureSample works on 10, but not 11 (in weird ways). 

OBS works on both using the same underlying apis. There has to be some nuanced difference in the core apis.

**Comment by rlewkowicz** [comment]
I built your rust object, and that worked. So I suppose ignore this. I'll debug further and reopen if needed.
